### PR TITLE
openstack/02b-MAChigh/msf.h: add ifndef guards

### PR DESCRIPTION
**Pull request by fjmolinas**
This PR simply adds some ifndef guards to allow easily modifying the values of the msf algorithm.

### CODE REVIEW

**Comment by fjmolinas** [comment]
Maybe @TimothyClaeys can take a look?

**Comment by TimothyClaeys** [comment]
@fjmolinas I think it is a good idea to make it easy to customize these values during compile time. Maybe you can add the ifdef guards to the `config.h` file, similar to how the values for `IEEE802154E_SINGLE_CHANNEL` or `PACKETQUEUE_LENGTH` are set.

**Review by TimothyClaeys — CHANGES_REQUESTED** [review]
Maybe add:

```
#ifndef MSF_MAX_NUMCELLS
#define MSF_MAX_NUMCELLS                   32
#endif
```
to the `config`.h file and replace the defines here with:
```
#ifndef MSF_MAX_NUMCELLS
#define MAX_NUMCELLS                   32
#else
#define MAX_NUMCELLS                   MSF_MAX_NUMCELLS 
#endif
```
In the `config.h` these values only are useful when `ADAPTIVE_MSF` is active. So maybe add an `#if` guard like we did for the `OPENWSN_6LO_FRAGMENTATION_C` options

**Comment by fjmolinas** [comment]
Done, lets see what travis says

**Comment by fjmolinas** [comment]
@TimothyClaeys all green here!

**Review by TimothyClaeys — APPROVED** [review]

**Comment by fjmolinas** [comment]
Thanks of the review!

**Pull request merged**
