### PR TITLE
FW-428. Fix. sixtop addCells does not add any cell.

### PR DESCRIPTION
**Pull request by victordzrz**

### CODE REVIEW

**Comment by twatteyne** [comment]
@changtengfei, could I ask you to commen on this fix.

**Comment by xvilajosana** [comment]
@changtengfei Hi Tengfei, is this fix related to FW-438 and FW-437 ? can you please comment on that?

thanks!
X

**Comment by changtengfei** [comment]
@victordzrz , thanks a lot for catching this. Since the 6tisch plugtest happened last month, this is fixed in the newer version of openwsn code. Do you mind I closed this pull request? The fixed code is at:
https://github.com/openwsn-berkeley/openwsn-fw/blob/develop/openstack/02b-MAChigh/processIE.c#L339
and
https://github.com/openwsn-berkeley/openwsn-fw/blob/develop/openstack/02b-MAChigh/sixtop.c#L901

**Comment by changtengfei** [comment]
Duplicated, so closed.

**Pull request closed without merging**
