### PR TITLE
FW-437. Fixed.

### PR DESCRIPTION
**Pull request by changtengfei**

### CODE REVIEW

**Comment by Erfanma** [comment]
Hi @changtengfei 
Why don't you use "MAXACTIVESLOTS"?? Because it is possible to have MAXACTIVESLOTS < schedule_getFrameLength().
Using "schedule_getFrameLength()" it's possible to add cells in OFF slotoffsets. Doesn't make problem??

**Comment by changtengfei** [comment]
@Erfanma , the slotoffset should be the number from 0 to slotframeLength-1, not from 0 to MAXACTIVESLOTS. MAXACTIVESLOTS is the buffer size of schedule.

**Comment by Erfanma** [comment]
@changtengfei,  your right. Thanks!

**Comment by changtengfei** [comment]
:-)

**Pull request merged**
