### PR TITLE
FW-16. FreeRTOS integration 

### PR DESCRIPTION
**Pull request by xvilajosana**
This is the freertos integration. It is well supported with armgcc motes and toolchain is ready for motes with enough memory. Tested in OpenMote cc2538. Gina and Telosb are not able to run it due to not enough memory. Compiling scripts and toolchain ready to choose target O.S. (e.g openos or freertos)

### CODE REVIEW

**Comment by xvilajosana** [comment]
@twatteyne this is failing because the travis CI is executing compilation for FreeRTOS in telosb and other not supported platforms. The failure happens because the scons build script raises a SystemException when the target platform freeRTOS is not supported. How can the builder be changed to do not compile this not supported platforms?

**Comment by twatteyne** [comment]
Simply update `.travis.yml` at the root of the repo. It contains the command that Travis executes.

**Comment by twatteyne** [comment]
@xvilajosana, I don't konw what to do with this PR. It all looks good, but since you can merge as well, I was wondering whether you were waiting for me to review, or whether the changes are not complete yet.

**Comment by xvilajosana** [comment]
I wanted you to review. Let's talk a little bit about it before merging this weekend :)
X

**Comment by twatteyne** [comment]
sounds good.

**Comment by changtengfei** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
