### PR TITLE
FW-656. 6LoRH deadline option implementation.

### PR DESCRIPTION
**Pull request by shalurajendran**
Implementation of the IETF draft "Packet expiration time in 6LoWPAN Routing Header"

The draft proposes to include packet expiration time in the packets which helps in realizing delay sensitive IoT applications over time synchronized networks such as 6tisch.

We included two applications, namely uexpiration and uexpiration_monitor to test the overall functionality of the implementation. More information is provided in the README files in the respective application folders.

Tested using OpenVisualizer of OpenWSN.

### CODE REVIEW

**Comment by changtengfei** [comment]
@shalurajendran I see you are still working on this PR. Could you confirm when you are done with it?
Usually before creating a PR, you should create an issue on the JIRA system and follow the workflow to work on that issue and create a PR when you are done: https://openwsn.atlassian.net/wiki/display/OW/Workflow

I will try to integrate your PR when you are done. For next, I would recommand follow the workflow to contribute. It's easier for me to integrate. Thanks!

**Comment by shalurajendran** [comment]
@changtengfei Sure, we will follow the workflow from next time. We are not able to complete the PR as test is failing for boards - telosb,wsn430v13b and wsn430v14 due to memory overflow, the build is successful for the rest of the boards. So could you please help us to rectify this issue.

**Comment by changtengfei** [comment]
@shalurajendran no problem I see the telosb and other msp430 based platform are not supported, could you add it back first? Then we can see how travis handle it.

**Comment by shalurajendran** [comment]
@changtengfei Yeah, we revert back to the original. Kindly go through and provide your inputs.

**Comment by changtengfei** [comment]
@shalurajendran it seems they are not only the ROM size problem, there are issues for the telosb board which is saying:

> build/telosb_mspgcc/openstack/02a-MAClow/IEEE802154E.c: In function ‘ieee154e_computeAsnDiff’:
> build/telosb_mspgcc/openstack/02a-MAClow/IEEE802154E.c:206:15: error: ‘PORT_RADIOTIMER_WIDTH’ undeclared (first use in this function)
> build/telosb_mspgcc/openstack/02a-MAClow/IEEE802154E.c:206:15: note: each undeclared identifier is reported only once for each function it appears in
> build/telosb_mspgcc/openstack/02a-MAClow/IEEE802154E.c:206:37: error: expected ‘;’ before numeric constant
> build/telosb_mspgcc/openstack/02a-MAClow/IEEE802154E.c:217:37: error: expected ‘;’ before numeric constant

**Comment by shalurajendran** [comment]
@changtengfei Ok,we modified the file to resolve the issue for telosb board. 
Now two conflicts are shown
- openwsnmodule.c modified to include a global variable required for testing our implementation
- openapps.c modified to call the init functions of the two new applications
Please provide inputs to resolve these conflicts.

**Comment by changtengfei** [comment]
@shalurajendran thanks for fixing the issue! For the conflicting files, that's caused by the deletion of tcp component. 
You can just delete all tcp related code. E.g.:
In openwsnmodule.c, delete all tcp_vars related code in the conflict part.
In openapps.c delete the techo initial function. 

I think it should be very straightforward for fixing the conflicts now. 
Besides that, could you explain how you verify this new feature? I saw there are two applications in the openapps.c. What does I suppose to see with this new applications? Thanks!

**Comment by shalurajendran** [comment]
@changtengfei Thanks. We have resolved the conflicts, as suggested. Now again the test fails for msp430 platforms like telosb due to ROM overflow. Is there anyway to solve this issue?

To test our implemenattaion, kindly go through the README file provided in the uexpiration and uexpiration_monitor applications. We have detailed the procedure to run. 

Kindly get back if you need more clarification, we will be happy to assist you.

**Comment by changtengfei** [comment]
@shalurajendran  I saw you fixed the issue. Thanks! For the ROM overflow problem, you can configure the two udp application (Sconscript file in openapps) as an compiling options that those two application can be compiled on demand. You needn't add the header and initial function in the openapps.c file.
I can do that if you want. It's easy to change.

**Comment by shalurajendran** [comment]
@changtengfei We tried to modify the SConscript file as suggested , but on testing it was found that the init was not called, so the application port was not getting registered. So if you could solve the issue, it would be great. Thanks in advance!!!

**Comment by changtengfei** [comment]
@shalurajendran no problem. Could you assign the right to access your repository?

**Comment by changtengfei** [comment]
@shalurajendran it seems the TCP module is still on your branch. Could you update your upstream repository(openwsn-berkeley/openwsn-fw) and merge it to your local? So the TCP component will be gone and save the memory.

**Comment by changtengfei** [comment]
Wait, it should be fine, the tcp files are presented but never been compiled.

**Comment by shalurajendran** [comment]
@changtengfei I provided the access. Kindly get back, if you find any difficulty.

**Comment by changtengfei** [comment]
@shalurajendran I tried with the code to not add the application by default but still failed because the other code added already exceed the limitation of telosb's ROM size. 
One way to solve the problem is disabling all application by default and only compiling apps on demand.
I am discussing with the OpenWSN team whether this makes sense. I will back to this.

**Comment by shalurajendran** [comment]
@changtengfei Thanks for the information. We do have the same feeling why the ROM overflow issue arises due to our addition. So kindly let us know once it is being solved. Please intimate if anything to be done from our end.

**Comment by changtengfei** [comment]
@shalurajendran I give the ball back to you. I just pushed two commits, could you check the first commit works for you? The second deable all application by default and apps will only compile with apps scons build option.

**Comment by shalurajendran** [comment]
@changtengfei Hihi.. Ok... Thank you..

We tested the code, but the application port is not registered, hence we are not able to run our applications. We experienced the same error when we moved the application init calls from openapps.c to SConscript.

Do we need to specify our applications in 'apps' utility of scons while compiling? But this feature is disabled for python board, isnt it so?

**Comment by changtengfei** [comment]
@shalurajendran I add all applications in simulation. You can try it now.

**Comment by shalurajendran** [comment]
@changtengfei Cool job!!! :+1: 

Now it works fine... Thanks for the support...

**Comment by changtengfei** [comment]
@shalurajendran I left some comments at https://openwsn.atlassian.net/browse/FW-656
Where is used for recording the discussion on this PR. I has two questions there and just want to understand more about the deadline applications you wrote. Could you answer them? You may need register as a user to left a comment.  Once you did that, I can @you when I reply so you can get the notification. Thanks a lot!

**Comment by shalurajendran** [comment]
@changtengfei Oh great...

We have replied your queries at https://openwsn.atlassian.net/browse/FW-656. Please have a look.

**Pull request merged**
