### PR TITLE
FW-408. Fixed.

### PR DESCRIPTION
**Pull request by changtengfei**

### CODE REVIEW

**Comment by xvilajosana** [comment]
@changtengfei  is this also solved in OpenWSN-SW?

as far as I remember, the OpenVisualizer also generates DIOs which may have a MOP option
https://github.com/openwsn-berkeley/openwsn-sw/blob/develop/software/openvisualizer/openvisualizer/RPL/RPL.py#L44

Not sure now if OV is generating the DIOs from the DAGRoot or this are generated by the FW side.
Can you confirm?

**Comment by changtengfei** [comment]
@xvilajosana ,  the DIO was generated by OV before, but now it moved to FW side. But I think what you pointed out need to be fixed, through it will not affect anything.

**Comment by xvilajosana** [comment]
I will open a new issue for SW to clean RPL defines in OV.

**Comment by twatteyne** [comment]
please don't forget to close the issues and delete branch after testin and merging

**Pull request merged**
