### PR TITLE
FW-751. Nordic nRF52840 port

### PR DESCRIPTION
**Pull request by dragondgold**
This port uses SEGGER Embedded Studio to develop.
The BSP, DRV and OOS projects are created for nRF52840. 

This port is tested with two nRF52840-DK boards.
One acts as dagroot, one acts as a regular node.
By programming with OpenWSN project code provided, the two nodes form a network.
The regular node is pingable.

### CODE REVIEW

**Comment by dragondgold** [comment]
Ok, the project now compiles using the following command:

`sudo scons board=nrf52840 revision=DK toolchain=armgcc oos_openwsn`

It successfully runs in the boards too (LEDs turn on and core is running). I still have to check if the network is running and operational, I will attach a logic analyzer to debug using the debugging pins provided by the port.

**Comment by changtengfei** [comment]
@dragondgold great news! I will check it out on my local and will comment on this PR after.

**Comment by changtengfei** [comment]
@dragondgold I tried with the PR however I encounter the following issue when compiling: 

```
arm-none-eabi-as -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -c -x assembler-with-cpp -DNRF52840_XXAA=1 -o
build\nrf52840_armgcc\bsp\boards\nrf52840\sdk\modules\nrfx\mdk\gcc_startup_nrf52840.o build\nrf52840
_armgcc\bsp\boards\nrf52840\sdk\modules\nrfx\mdk\gcc_startup_nrf52840.S
arm-none-eabi-as: unrecognized option `-x'
scons: *** [build\nrf52840_armgcc\bsp\boards\nrf52840\sdk\modules\nrfx\mdk\gcc_startup_nrf52840.o] E
rror 1
scons: building terminated because of errors.
```

Do you have this issue? By searching online, it tells the assembly file suffix should be '.S' instead of '.s'. But it does end with '.S'

**Comment by changtengfei** [comment]
@dragondgold I tried this branch on Linux and the compile passed. I will check what's going on on Windows.   Beside,  the bootload is not supported for nRF52840. How do you problem the DK board?

**Comment by changtengfei** [comment]
@dragondgold I found the emProject and tried to program the board,  after comment out the openapp_init() function,  the project compiles.   After I flash two DK boards, when running OpenVisualizer, it's hardly to recognized their serial port.  Sometime it recognized but with an error triggered in the OpenVisualizer  terminal indicating 

```
======= crash in moteProbe@COM84 =======
Error:


call stack:

Traceback (most recent call last):
  File "C:\Users\Tengfei\Desktop\nodirc_port\openvisualizer\openvisualizer\moteProbe\moteProbe.py", line 349, in run
    self.inputBuf        = self.hdlc.dehdlcify(self.inputBuf)
  File "C:\Users\Tengfei\Desktop\nodirc_port\openvisualizer\openvisualizer\moteProbe\OpenHdlc.py", line 99, in dehdlcify
    assert inBuf[-1]==self.HDLC_FLAG
AssertionError
```

Then I went to the uart.c implementation, it seems the clear/enable/disable interrupts for Tx and Rx are not implemented, also the implementation for uart_writeByte doesn't support XON/XOFF feature.  You can take the uart.c of OpenMote-B 24GHz as an example to fix the implementation. 

For the current epidemic  situation, let me know  if you don't have time to work on that. So that I can take over the work if you don't mind.

**Comment by dragondgold** [comment]
Hi @changtengfei! I'm so sorry for the late reply, of course, you can take over the work! I haven't had time to continue it. I compiled everything in Ubuntu and flashed the device using [nrfutil](https://github.com/NordicSemiconductor/pc-nrfutil)

**Comment by kyh-ly** [comment]
I find this project and I want to know why to configure the UART by directly accessing the register instead of using the app_uart_init() function.

**Pull request merged**
