### PR TITLE
FW-407. fixed.

### PR DESCRIPTION
**Pull request by changtengfei**

### CODE REVIEW

**Comment by twatteyne** [comment]
@changtengfei , I can't merge this automatically, could you verify why and commit a fix that will allow me to? Let me know if you don't have time and I can do it.

**Comment by twatteyne** [comment]
cannot merge automatically. waiting for fix. tests pass.

**Comment by changtengfei** [comment]
In FW-406, I fixed the issue by using a 16bit local address as source address. In FW-407, the source address are totally elided. If possible, we should reverse what did in FW-406 and only merge with FW-407.

**Comment by twatteyne** [comment]
I created https://github.com/openwsn-berkeley/openwsn-fw/pull/200, waiting for it to pass the build, then I will revert.

**Comment by xvilajosana** [comment]
tested and works

**Comment by twatteyne** [comment]
deleting branch and closing issue

**Pull request merged**
