### PR TITLE
FW-681 merged develop branch, fixed line endings

### PR DESCRIPTION
**Pull request by chris-ho**

### CODE REVIEW

**Comment by chris-ho** [comment]
@malishav now everything should be clean. my git tool automatically changes all line endings to CR LF

**Comment by chris-ho** [comment]
@malishav now everything should be clean. my git tool automatically changes all line endings to CR LF

**Comment by malishav** [comment]
Hi @chris-ho, 

Big thanks for doing this work. We are almost there. I still see a huge diff on `cinfo.c` and `opencoap.h` files. Could you make sure that only the diff of the lines you actually modified appears in the PR. Then we should be able to merge.

**Comment by chris-ho** [comment]
@malishav that's related to trailing whitespaces

**Comment by malishav** [comment]
If you could fix that those lines do not appear in the PR, that would be great. This is to minimize the probability of the changed lines causing conflicts on other people's branches when they try to merge with upstream. FYI, git-cola is a nice graphical tool for selectively committing only the specific lines from all the change-set in a file. You can do the same with git CLI but it's more tedious.

**Comment by chris-ho** [comment]
argghhh i reverted the previous commit, then used notepad for editing my files instead of iar, then i checked diff to HEAD only the the modified lines have shown up as is should be then after commit and push everything messed up ???

**Comment by malishav** [comment]
I think that the best way to proceed would be to:
- remove `1d2a16f` and start from `60b96ae`
- revert changes only on `cinfo.c` and `opencoap.h` (i.e. git checkout origin/develop -- filename)
- edit `cinfo.c` and `opencoap.h` with notepad for example
- commit only the edited lines with git-cola

Let me know if that works.

**Comment by chris-ho** [comment]
@malishav  i'm sorry it doesn't work. see below the diff i got **bold** removed parts _italic_ new parts.
git  config.autocrlf is false

$ git diff HEAD
diff --git a/openapps/cinfo/cinfo.c b/openapps/cinfo/cinfo.c
index 5297a29..b31846f 100644
--- a/openapps/cinfo/cinfo.c
+++ b/openapps/cinfo/cinfo.c
@@ -106,13 +106,14 @@ 

**packetfunctions_reserveHeaderSize(msg,sizeof(infoStackName)-1+5);**
_packetfunctions_reserveHeaderSize(msg,sizeof(infoStackName)-1+6);_
memcpy(&msg->payload[0],&infoStackName,sizeof(infoStackName)-1);
**msg->payload[sizeof(infoStackName)-1+5-5] = '0'+OPENWSN_VERSION_MAJOR;**
**msg->payload[sizeof(infoStackName)-1+5-4] = '.';**
**msg->payload[sizeof(infoStackName)-1+5-3] = '0'+OPENWSN_VERSION_MINOR;**
**msg->payload[sizeof(infoStackName)-1+5-2] = '.';**
**msg->payload[sizeof(infoStackName)-1+5-1] = '0'+OPENWSN_VERSION_PATCH;**
_msg->payload[sizeof(infoStackName)-1+6-6] = '0'+OPENWSN_VERSION_MAJOR;_
_msg->payload[sizeof(infoStackName)-1+6-5] = '.';_
_msg->payload[sizeof(infoStackName)-1+6-4] = '0'+OPENWSN_VERSION_MINOR / 10;_
_msg->payload[sizeof(infoStackName)-1+6-3] = '0'+OPENWSN_VERSION_MINOR % 10;_
_msg->payload[sizeof(infoStackName)-1+6-2] = '.';_

diff --git a/openapps/opencoap/opencoap.h b/openapps/opencoap/opencoap.h
index 3f031db..84f7d13 100644
--- a/openapps/opencoap/opencoap.h
+++ b/openapps/opencoap/opencoap.h
@@ -245,7 +245,7 @@ 


**coap_option_iht\* opencoap_find_option(coap_option_iht\* array, uint8_t arrayLen, coap_option_t option);**

_uint8_t opencoap_find_option(coap_option_iht* array, uint8_t arrayLen, coap_option_t option, uint8_t* startIndex);_

**Comment by chris-ho** [comment]
if i check the commit on my fork it looks good so far
https://github.com/chris-ho/openwsn-fw/commits/develop_FW-681

yesterdays commit also had huge diffs but current commit is clean

**Comment by malishav** [comment]
I suggest that we wait then until @changtengfei merges the FW-684. Once that is done, a rebase should do it.

**Comment by chris-ho** [comment]
finally that sould solve my problem

**Comment by chris-ho** [comment]
i reopend a new PR https://github.com/openwsn-berkeley/openwsn-fw/pull/393 where the line ending problem is solved

**Pull request closed without merging**
