### PR TITLE
udp application which send the packet contain asn data

### PR DESCRIPTION
**Pull request by kyh-ly**
I have created the UDP application which periodically send the packet only contains the asn ,but when i send the packet and run the OpenVisuallizer , the terminal shows :[ICMPV6] unsupported type 137(location code 1).
if the packet can not send the upper layer and the receiver 's msg->l4_sourceORicmpv6type is wrong. Can you give me some advice or I need to give you the code >

### CODE REVIEW

**Comment by changtengfei** [comment]
@kyh-ly I realize you are developing code based my personal fork develop branch OpenWSN code, which not up-to-date at all. 

To implement what you are trying to do, it's better to use the latest develop branch code from Open Visualizer and OpenWSN-FW codes.  I would more recommend to  modify directly the uinject.c file before writing a new one. Try to see how the latency is calculate there first here: https://github.com/openwsn-berkeley/openvisualizer/blob/develop/openvisualizer/motehandler/moteconnector/openparser/parserdata.py#L108

once you figure out how this works, it should be straightforward for you to write your own app.

**Comment by kyh-ly** [comment]
This is the first time I use the Github If I operate error, I apologize to you. @changtengfei 
I don't understand why the variable asn_bytes  can get the ASN from the data[2:7] ,  if the destinate mote 's local ASN can be added to the data before send it to the UDP layer. If I create a UDP application that receives the UDP packet , do I should parse data like the PareserData? I add the the my UDP application code to the openwsn.org. You can see it and when I run it using OpenVisuallizer，the terminal shows ERROR 2[ICMPV6] unsupported type 137(location code 1).

**Comment by kyh-ly** [comment]
I think the new openvisualizer is difficult to use, and the simulation can not.work,i dont know how  to operat it




| |
kyhline
邮箱：kyh1511226779@163.com
|

Signature is customized by Netease Mail Master

On 06/19/2020 17:47, Tengfei.Chang wrote:

@kyh-ly I realize you are developing code based my personal fork develop branch OpenWSN code, which not up-to-date at all.

To implement what you are trying to do, it's better to use the latest develop branch code from Open Visualizer and OpenWSN-FW codes. I would more recommend to modify directly the uinject.c file before writing a new one. Try to see how the latency is calculate there first here: https://github.com/openwsn-berkeley/openvisualizer/blob/develop/openvisualizer/motehandler/moteconnector/openparser/parserdata.py#L108

once you figure out how this works, it should be straightforward for you to write your own app.

**Comment by kyh-ly** [comment]
@changtengfei I know that when running the uinject application on the openvisualizer, the ParserData will parse the UDP data. I saw `when the packet goes to the internet it comes with the asn at the beginning as timestamp`, as I know the latency which it computes is the time between packet generation and network access.

**Comment by kyh-ly** [comment]
@changtengfei @thomaseichinger I don't know why the uinject application running, the mote can not receive the packet on the UDP layer with the udp_receive callback function is set.

**Comment by kyh-ly** [comment]
> @kyh-ly I realize you are developing code based my personal fork develop branch OpenWSN code, which not up-to-date at all.
> 
> To implement what you are trying to do, it's better to use the latest develop branch code from Open Visualizer and OpenWSN-FW codes. I would more recommend to modify directly the uinject.c file before writing a new one. Try to see how the latency is calculate there first here: https://github.com/openwsn-berkeley/openvisualizer/blob/develop/openvisualizer/motehandler/moteconnector/openparser/parserdata.py#L108
> 
> once you figure out how this works, it should be straightforward for you to write your own app.

**Comment by TimothyClaeys** [comment]
Is this PR still active? Otherwise we can close it.

**Pull request closed without merging**
