### PR TITLE
FW-490. [ADD] MoteISTv5 Project Folder

### PR DESCRIPTION
**Pull request by MrD2**
This will replace #FW-490. Add support for MSP430X processors

Because, this pull request will join all my project

For now, i'm just testing if i didnt break your compilation environment as i'll be adding the new mspgcc as a 'different' tool chain (newmspgcc) to maintain some backward compatibility without extensive changes, later we can then work and unify them....

### CODE REVIEW

**Comment by MrD2** [comment]
# **THIS IS NOT YET IMPLEMENTED. I'M TESTING STUFF**

# I'LL ADVISE FOR REVISION

**Comment by MrD2** [comment]
@changtengfei by any chance you don't know how i use sudo on -travis.yml ?

**Comment by changtengfei** [comment]
@MrD2 I didn't know what you are saying? :-)

**Comment by MrD2** [comment]
Never mind @changtengfei,

Already solved the issue "kinda - i cheated"

I'm still going to test my stuff, so... not ready yet, but the compiler is already available ;)

**Comment by MrD2** [comment]
I'm deleting this until i have everything ok

**Pull request closed without merging**
