### PR TITLE
FW-234 SCons build for Atmel SAMR21-XPlained Pro

### PR DESCRIPTION
**Pull request by mikehaben**
Re-implemented from latest version of master repo, and with FW-234 changes committed this time!

### CODE REVIEW

**Comment by mikehaben** [comment]
Not accepted so far.  Need to close this in order to send a new pull-request for a different patch.

**Comment by changtengfei** [comment]
@mikehaben , because of there is no such folder in openwsn directory:

-Tbsp/boards/samr21_xpro/cmsis/linkerScripts/samr21g18a_flash.ld

which is used when calling SCons command.

**Comment by mikehaben** [comment]
Oh dear, must apologise - I'm getting really confused by Git/Github.  My commit 5f9ba20 fixed this, but I don't know how to "add" it to the pull-request.  I might have to delete and re-create my fork of openwsn-fw!
Full URL of this commit is: 
https://github.com/mikehaben/openwsn-fw/commit/5f9ba20ab85c6149e98083ae2de197a0dfb482ea

**Comment by twatteyne** [comment]
@mikehaben , you can just continue to commit to the same fork, it will automatically update the PR

**Pull request closed without merging**
