### PR TITLE
FW-635. Replace bsp_timer and radiotimer by a single timer (sctimer) implementation.

### PR DESCRIPTION
**Pull request by changtengfei**

### CODE REVIEW

**Comment by changtengfei** [comment]
@xvilajosana @twatteyne if you have time, you could review the PR. For my side, the openmote-cc2538, openmotestm (stm32f103 platform), and telosb (msp430 platform) has been tested over nights and they works well.

**Comment by xvilajosana** [comment]
@changtengfei We had some nodes running. They kept synch well. However I tried the simulator with the changes in the code and fails to run due to errors in the BSP level emulation. 

created following virtual interface:
6: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 500
    link/none 
    inet6 bbbb::1/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::1/64 scope link 
       valid_lft forever preferred_lft forever
Traceback (most recent call last):
  File "bin/openVisualizerApp/openVisualizerWeb.py", line 614, in <module>
    app      = openVisualizerApp.main(parser, argspace.roverMode)
  File "/home/xvilajosana/Development/workspaces/openwsn/openwsn-clean/head/openwsn-sw/software/openvisualizer/bin/openVisualizerApp/openVisualizerApp.py", line 327, in main
    roverMode       = roverMode
  File "/home/xvilajosana/Development/workspaces/openwsn/openwsn-clean/head/openwsn-sw/software/openvisualizer/bin/openVisualizerApp/openVisualizerApp.py", line 90, in __init__
    moteHandler       = MoteHandler.MoteHandler(oos_openwsn.OpenMote())
  File "/home/xvilajosana/Development/workspaces/openwsn/openwsn-clean/head/openwsn-sw/software/openvisualizer/openvisualizer/SimEngine/MoteHandler.py", line 99, in __init__
    mote.set_callback(notifId('bsp_timer_init'),                      self.bspBsp_timer.cmd_init)
  File "/home/xvilajosana/Development/workspaces/openwsn/openwsn-clean/head/openwsn-sw/software/openvisualizer/openvisualizer/SimEngine/MoteHandler.py", line 53, in notifId
    assert s in notifString
AssertionError

**Comment by changtengfei** [comment]
@xvilajosana there is also openwsn-sw PR coming along with openwsn-fw PR. The error is saying bsp_timer but in the new code, we don't have bsp_timer module anymore, just BSPSctimer.py
https://github.com/openwsn-berkeley/openwsn-sw/pull/143

**Comment by changtengfei** [comment]
@xvilajosana have you tried with the updated openwsn-sw code?

**Comment by xvilajosana** [comment]
Hi Tengfei,

yes sorry I tested and worked! sorry for not closing this!

**Comment by changtengfei** [comment]
Thanks a lot @xvilajosana  for the confirmation! I will merge it now.

**Pull request merged**
