### PR TITLE
MAC: fix potentially uninitialized variable

### PR DESCRIPTION
**Pull request by PeterKietzmann**
This PR sets initial values to some variables. Compiler warnings complained about potential use of uninitialized variables.

### CODE REVIEW

**Comment by changtengfei** [comment]
@PeterKietzmann the unassigned variables are variables to be determined in process. I don't think it's required to initialize them.

**Comment by PeterKietzmann** [comment]
Yes, that's why they will be overwritten. However, there might be corner cases. At least the compiler complains about them being uninitialized.

**Comment by changtengfei** [comment]
Peter, the compiler should be able detect, if it's defined inside of the function later, it shouldn't complaint.  Which compiler you are using, somehow I can compile the code without any warning.

**Comment by PeterKietzmann** [comment]
I'm using arm-none-eabi-gcc 5.4.1. This problem occurred when  compiling OpenWSN as part of the integration in RIOT. There, we enable compiler warnings and treat them as errors. See this excerpt as an example, where I at least disabled to handle warnings as errors:

```
/media/Data/RIOT/tests/openwsn/bin/pkg/nucleo-f103/openwsn-fw/openstack/02a-MAClow/IEEE802154.c: In function 'ieee802154_prependHeader':
/media/Data/RIOT/tests/openwsn/bin/pkg/nucleo-f103/openwsn-fw/openstack/02a-MAClow/IEEE802154.c:175:7: warning: 'destAddrMode' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (destAddrMode == IEEE154_ADDR_SHORT) {
```

If you don't want this fix in your code, just close the. Then I need a proper patch as part of the RIOT integration.

**Comment by changtengfei** [comment]
@PeterKietzmann I would like see the same what you saw with the warning. For now, is that possible for me to reproduce this warning?
Even finally we are going to have this fix, I would like to replace the -1 by enum type, which I can add them.

**Comment by PeterKietzmann** [comment]
Fine. I'll push everything once #410 was merged. Will give some further details about reproducing it afterwards. We can close this PR then.

**Comment by PeterKietzmann** [comment]
@changtengfei now that you have seen these warnings, what do you think about this PR?

**Comment by changtengfei** [comment]
Thank you @PeterKietzmann !

**Pull request merged**
