### PR TITLE
FW-394. Fixed.

### PR DESCRIPTION
**Pull request by changtengfei**
Update l4_protocol_compressed by next_header_compressed of ipv6 inner header.

### CODE REVIEW

**Comment by twatteyne** [comment]
excellent!!
Can you describe how you test this fix?

**Comment by changtengfei** [comment]
I forgot to update the NH_COMPRESS filed by ipv6 inner header, I added one line code here:
https://github.com/openwsn-berkeley/openwsn-fw/blob/develop_FW-394/openstack/03b-IPv6/forwarding.c#L504

That's all how I fixed it.

**Comment by changtengfei** [comment]
There are another line I modified, which I should use l4_protocol as the NH filed.

**Comment by twatteyne** [comment]
@changtengfei , I meant how to test this? i.e. can you describe what tests you ran before submitting the fix. I assume that you tried to use CoAP in simulation, maybe ran on real HW, etc.

**Comment by changtengfei** [comment]
Oh I see, sorry!

I tested it with a simulation network of 3 motes in linear topology. After get the DAO information, I try to get the cstorm value of mote 03 and succeeded with ietf90client.py.

**Comment by twatteyne** [comment]
@changtengfei , could I ask you to do the following:
- 3-note linear network 1-2-3
- ping mote 3
- use Copper Firefox pluging to retrieve /i resource

**Comment by Erfanma** [comment]
I tried the develop_fw-394 but still have that error!!

**Comment by twatteyne** [comment]
@changtengfei, please see comment from @Erfanma 

Almost there!!

**Comment by Erfanma** [comment]
@twatteyne  I thought These changes are related to the problem I reported yesterday.
If it is related to your CoAP error I did not check it.
Sorry

**Comment by twatteyne** [comment]
@Erfanma , no problem, of course!
I believe these changes fix the fact that CoAP stopped working after all of the changes.
What did you report? Can you point me to an issue on openwsn.org?
[sorry, many things happening, I don't recall everything]

**Comment by Erfanma** [comment]
@twatteyne  This is the problem that you suggested to use latest release instead.

"I use UINJECT application. When udp packet is received by relay node and creator is changed to COMPONENT_FORWARDING,  value of variable "l4_protocol" must be 0x11 but changes  to 238 in decimal which is strange!!"

If needed I can make an issue.

**Comment by changtengfei** [comment]
Sure, I will do it 15mins later after when I back to my computer.

Thomas Watteyne <notifications@github.com>编写：

**Comment by twatteyne** [comment]
Thanks!

**Comment by twatteyne** [comment]
@Erfanma, I thought @xvilajosana indicated that this was, in fact related. So in my mind @changtengfei 's fix would also fix your problem. I don't think I fully understand then. I'll let @changtengfei and @xvilajosana chime in.

**Comment by Erfanma** [comment]
No, it did not fix it.
Thanks!

**Comment by twatteyne** [comment]
OK!

**Comment by changtengfei** [comment]
@twatteyne @xvilajosana @Erfanma , I tested as what Thomas said, and it works with more than one hop but failed when I retrieve /i resource of one hop mote. This is because for one hop there is no source routing header. What I fixed before is for the case when there is source routing in the packet. Currently, this is fixed at:
https://github.com/openwsn-berkeley/openwsn-fw/commit/de5749700cfe7143ea917cb4237e8c86be8e6d4b

@Erfanma , could you confirm this fix works for you?

**Comment by twatteyne** [comment]
@changtengfei , thank you for working so hard on this!
I didn't quite understand, did you fix this already or is the 1-hop case an open issue?
Thanks

**Comment by changtengfei** [comment]
@twatteyne , there are two places in the code that will check the next header in ipv6 inner header. One is processed after processing source routing header, one is processed after retrieving the ipv6 outer header when there is no source routing. Both cases I forgot to update the nh_compressed field by ipv6 inner header. First time, I fixed the case for source routing header, this time, I fixed the case for no source routing header.

This is one issue that should be done at once, sorry I did it twice.

**Comment by Erfanma** [comment]
@changtengfei , I made the changes but did not work for me!! As soon as 2-hop nodes join the network, it occurs!

**Comment by changtengfei** [comment]
@Erfanma , what kind of error have you seen? Could you show it? For me, I do be able to get the resource from Copper firefox, no matter one hop or two hops motes.

@twatteyne @xvilajosana , if you have time, could you try the code and confirm whether this works on your side?

**Comment by Erfanma** [comment]
@changtengfei , in function "openqueue_macGetDataPacket()" from openqueue.c , I have a if statement that filters non-udp packets "if(openqueue_vars.queue[i].l4_protocol == IANA_UDP)".
So non-udp packets stays in queue till the queue overflows. UDP packets which are 2-hop away from the sink when reaches to 1-hop remains in queue and can not be forwarded. The strange part is that for udp packets which their creator is "COMPONENT_FORWARDING" l4_protocol value is 238 in decimal and can not pass the if statement!!
I should notice that it was working fine before your recent changes such as IP-in-IP encapsulation .

**Comment by xvilajosana** [comment]
Hi,

just to clarify and maybe help, the problem happens only when a relayed packet reaches the 1st hop before forwarding to the sink.

Relaying function sets the creator of the packet to FORWARDING here
https://github.com/openwsn-berkeley/openwsn-fw/blob/develop_FW-394/openstack/03b-IPv6/forwarding.c#L274

I guess that the problem might be related to the fact that when receiving a packet to be relayed the l4_protocol is not being updated in here as the condition above do not apply
 
https://github.com/openwsn-berkeley/openwsn-fw/blob/develop_FW-394/openstack/03b-IPv6/forwarding.c#L242

instead, the packet is forwarded by re-appending all IPHC headers and not touching the payload. 
https://github.com/openwsn-berkeley/openwsn-fw/blob/develop_FW-394/openstack/03b-IPv6/forwarding.c#L276

it seems that  l4_protocol in the queue is is pointing to the inner IP header.

I might be able to anticipate that if instead of 3 motes (2 hops) you use 4 motes, after the 1st hop you will see the same problem, so this is not a problem of the last hop but a problem of the relaying function that will affect all intermediate hops before the sink.

This was working before because we had the UDP header following the inner header. Now the outer header points to the inner header which points to the udp header. The l4_protocol points to the inner header in case of relaying. 

This might be correct as in that case we do not care on the UDP header as we are relaying. However I think that changing the l4_protocol analogously to what is done 
https://github.com/openwsn-berkeley/openwsn-fw/blob/develop_FW-394/openstack/03b-IPv6/forwarding.c#L241

somewhere here
https://github.com/openwsn-berkeley/openwsn-fw/blob/develop_FW-394/openstack/03b-IPv6/forwarding.c#L275

might make things work while keeping same behaviour as before.

**Comment by Erfanma** [comment]
@xvilajosana  @changtengfei  , as you anticipated it is not only related to the 1st hop, it affects all intermediate hops before the sink.

As you mentioned this might be correct do not pay attention on the UDP header in relaying, but I am working on scheduling and have to filter the packets in openqueue to distinguish data packets from others and send them in dedicated cells.
However if udp headers are not important in that place, it is no matter. I try to find another way :)

I tested your suggestion in the last paragraph, but it  crashes when second hop nodes join the network!

======= crash in moteProbe@emulated1 =======
Error:
'next_header'

**Comment by twatteyne** [comment]
@changtengfei , any progress on this issue? Should I merge the code now in the PR?

**Comment by changtengfei** [comment]
I am not sure, currently only I myself say this works, I have received two error reports from @Erfan and Sedat Bilgili (see https://openwsn.atlassian.net/browse/FW-394). But I do test the simulation again with the Copper Firefox plugin(first "discover" and then "get" on i), and it works.

@twatteyne , @xvilajosana , If you have time, could you try the code to test whether this fixed works for you?

**Comment by Erfanma** [comment]
@changtengfei , Yesterday I sent you a message and told that it works fine.
The only problem is what I mentioned (can not access l4_protocol in openqueue.c) and it is my problem not yours!!

**Comment by twatteyne** [comment]
That's great news! Tengfei, could I ask you to merge this PR?

**Comment by changtengfei** [comment]
Oh, thanks a lot for your feedback, @Erfan. Sorry I didn't notice that your message!

I will merge this one.

**Comment by Erfanma** [comment]
No problem!! It's OK.
My id is @Erfanma , not @Erfan. Erfan is someone else!! :)

**Comment by changtengfei** [comment]
Oh I See, @Erfanma  Sorry for this mistake!

I just merged FW-392 into develop, then merged develop to this pull request. After this issue passed the travis check, I will merge this one.

**Comment by twatteyne** [comment]
Thanks Tengfei!

**Pull request merged**
